In [1]:
import polars as pl

df = pl.read_csv("./collected_data.csv")

df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ victim_an ┆ victim_ve ┆ victim_bl ┆ victim_w │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ gle       ┆ rt_angle  ┆ inded     ┆ eapon    │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ bool      ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ USP-S    │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ USP-S    │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Glock-18 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [2]:
def weapon_parse(w):
    if w in {"AK-47", "M4A4", "AUG", "SCAR-20", "M4A1", "FAMAS", "Galil AR", "SG 553"}:
        return "Rifle"
    elif w in {
        "P2000",
        "USP-S",
        "Glock-18",
        "P250",
        "Five-SeveN",
        "Tec-9",
        "CZ75-Auto",
        "CZ75 Auto",
        "Dual Berettas",
        "Desert Eagle",
        "R8 Revolver",
    }:
        return "Pistol"
    elif w in {"Nova", "XM1014", "MAG-7", "Sawed-Off"}:
        return "Shotgun"
    elif w in {"MP9", "MAC-10", "PP-Bizon", "MP7", "UMP-45", "P90", "MP5-SD"}:
        return "SMG"
    elif w in {"SSG 08", "AWP", "SCAR-20", "G3SG1"}:
        return "Sniper"
    elif w in {"M249", "Negev"}:
        return "Machine Gun"
    elif w in {
        "HE Grenade",
        "Molotov",
        "Incendiary Grenade",
        "Smoke Grenade",
        "Decoy Grenade",
        "Flashbang",
        "Flash Grenade",
    }:
        return "Grenade"
    elif w in {"Knife", "Zeus x27", "C4"}:
        return "Melee"
    else:
        return w

In [3]:
df = df.with_columns(
    pl.col("attacker_weapon").map_elements(weapon_parse, return_dtype=pl.String)
)
df = df.with_columns(
    pl.col("victim_weapon").map_elements(weapon_parse, return_dtype=pl.String)
)
df.select("attacker_weapon").unique()
df.select("victim_weapon").unique()

shape: (8, 1)
┌───────────────┐
│ victim_weapon │
│ ---           │
│ str           │
╞═══════════════╡
│ Pistol        │
│ Sniper        │
│ Shotgun       │
│ Melee         │
│ Grenade       │
│ Rifle         │
│               │
│ SMG           │
└───────────────┘

In [4]:
cols = []
for key in df.collect_schema():
    if key not in {
        "kill_tick",
        "duel_tick",
        "kill_seconds",
        "duel_seconds",
        "attacker_weapon",
        "victim_weapon",
    }:
        cols.append(key)
print(cols)

['distance', 'attacker_vel', 'attacker_vel_dir', 'attacker_vz', 'attacker_side', 'attacker_hp', 'attacker_helmet', 'attacker_armor', 'attacker_spotted', 'attacker_angle', 'attacker_vert_angle', 'attacker_blinded', 'victim_vel', 'victim_vel_dir', 'victim_vz', 'victim_hp', 'victim_helmet', 'victim_armor', 'victim_spotted', 'victim_angle', 'victim_vert_angle', 'victim_blinded']

In [5]:
cols = []
for key in df.collect_schema():
    cols.append(key)
print(cols)

['kill_tick', 'kill_seconds', 'duel_tick', 'duel_seconds', 'distance', 'attacker_vel', 'attacker_vel_dir', 'attacker_vz', 'attacker_side', 'attacker_hp', 'attacker_helmet', 'attacker_armor', 'attacker_spotted', 'attacker_angle', 'attacker_vert_angle', 'attacker_blinded', 'attacker_weapon', 'victim_vel', 'victim_vel_dir', 'victim_vz', 'victim_hp', 'victim_helmet', 'victim_armor', 'victim_spotted', 'victim_angle', 'victim_vert_angle', 'victim_blinded', 'victim_weapon']

In [6]:
for col in cols:
    df = df.rename({col: col.replace("attacker", "player_1")})
df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ victim_an ┆ victim_ve ┆ victim_bl ┆ victim_w │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ gle       ┆ rt_angle  ┆ inded     ┆ eapon    │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ bool      ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
for col in cols:
    df = df.rename({col: col.replace("victim", "player_2")})
df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ angle     ┆ vert_angl ┆ blinded   ┆ _weapon  │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ bool      ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
new_df = df.clone()
new_df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ angle     ┆ vert_angl ┆ blinded   ┆ _weapon  │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ bool      ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
cols = []
for key in new_df.collect_schema():
    cols.append(key)
for col in cols:
    new_df = new_df.rename({col: col.replace("player_1", "temporary")})
new_df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ angle     ┆ vert_angl ┆ blinded   ┆ _weapon  │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ bool      ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
cols = []
for key in new_df.collect_schema():
    cols.append(key)
for col in cols:
    new_df = new_df.rename({col: col.replace("player_2", "player_1")})
new_df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_1_ ┆ player_1_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ angle     ┆ vert_angl ┆ blinded   ┆ _weapon  │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ bool      ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
cols = []
for key in new_df.collect_schema():
    cols.append(key)
for col in cols:
    new_df = new_df.rename({col: col.replace("temporary", "player_2")})
new_df.head(n=3)

shape: (3, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_1_ ┆ player_1_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ angle     ┆ vert_angl ┆ blinded   ┆ _weapon  │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ bool      ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.431135  ┆ 0.317324  ┆ true      ┆ Pistol   │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 2.352172  ┆ 6.824736  ┆ false     ┆ Pistol   │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ 114.72772 ┆ -15.30569 ┆ false     ┆ Pistol   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df = df.with_columns(pl.lit(True).alias("player_1_win"))
df.head(n=3)

shape: (3, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ vert_angl ┆ blinded   ┆ weapon    ┆ _win     │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ e         ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ ---       ┆ bool      ┆ str       ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.317324  ┆ true      ┆ Pistol    ┆ true     │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 6.824736  ┆ false     ┆ Pistol    ┆ true     │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ -15.30569 ┆ false     ┆ Pistol    ┆ true     │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
new_df = new_df.with_columns(pl.lit(False).alias("player_1_win"))
new_df.head(n=3)

shape: (3, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_1_ ┆ player_1_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ vert_angl ┆ blinded   ┆ weapon    ┆ _win     │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ e         ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ ---       ┆ bool      ┆ str       ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ 0.317324  ┆ true      ┆ Pistol    ┆ false    │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ 6.824736  ┆ false     ┆ Pistol    ┆ false    │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ -15.30569 ┆ false     ┆ Pistol    ┆ false    │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
new_df = new_df.with_columns(
    (pl.col("player_2_side") == "ct").alias("player_1_terrorist")
)
new_df = new_df.drop("player_2_side")
new_df.head(n=3)

shape: (3, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_1_ ┆ player_1_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ blinded   ┆ weapon    ┆ win       ┆ _terrori │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ st       │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ bool      ┆ str       ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ true      ┆ Pistol    ┆ false     ┆ false    │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ false     ┆ Pistol    ┆ false     ┆ false    │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ false     ┆ Pistol    ┆ false     ┆ true     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
def df_side(s):
    return s == "t"


df = df.with_columns((pl.col("player_1_side") == "t").alias("player_1_terrorist"))
df = df.drop("player_1_side")
df.head(n=3)

shape: (3, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ blinded   ┆ weapon    ┆ win       ┆ _terrori │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ st       │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ bool      ┆ str       ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ true      ┆ Pistol    ┆ true      ┆ true     │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ false     ┆ Pistol    ┆ true      ┆ true     │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ false     ┆ Pistol    ┆ true      ┆ false    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
total_df = pl.concat([df, new_df], how="diagonal")
total_df.head(n=3)

shape: (3, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_1_ ┆ player_1 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ blinded   ┆ weapon    ┆ win       ┆ _terrori │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ st       │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ bool      ┆ str       ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ true      ┆ Pistol    ┆ true      ┆ true     │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ false     ┆ Pistol    ┆ true      ┆ true     │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ false     ┆ Pistol    ┆ true      ┆ false    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
def weapon_check(target):
    def check(weapon):
        return weapon == target

    return check

In [18]:
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Rifle").alias("player_1_rifle")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Pistol").alias("player_1_pistol")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Sniper").alias("player_1_sniper")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Melee").alias("player_1_melee")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "SMG").alias("player_1_smg")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Grenade").alias("player_1_grenade")
)
total_df = total_df.with_columns(
    (pl.col("player_1_weapon") == "Shotgun").alias("player_1_shotgun")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Rifle").alias("player_2_rifle")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Pistol").alias("player_2_pistol")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Sniper").alias("player_2_sniper")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Melee").alias("player_2_melee")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "SMG").alias("player_2_smg")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Grenade").alias("player_2_grenade")
)
total_df = total_df.with_columns(
    (pl.col("player_2_weapon") == "Shotgun").alias("player_2_shotgun")
)

In [19]:
for col, dtype in total_df.schema.items():
    print(col, dtype)

kill_tick Int64
kill_seconds Float64
duel_tick Int64
duel_seconds Float64
distance Float64
player_1_vel Float64
player_1_vel_dir Float64
player_1_vz Float64
player_1_hp Int64
player_1_helmet Boolean
player_1_armor Boolean
player_1_spotted Boolean
player_1_angle Float64
player_1_vert_angle Float64
player_1_blinded Boolean
player_1_weapon String
player_2_vel Float64
player_2_vel_dir Float64
player_2_vz Float64
player_2_hp Int64
player_2_helmet Boolean
player_2_armor Boolean
player_2_spotted Boolean
player_2_angle Float64
player_2_vert_angle Float64
player_2_blinded Boolean
player_2_weapon String
player_1_win Boolean
player_1_terrorist Boolean
player_1_rifle Boolean
player_1_pistol Boolean
player_1_sniper Boolean
player_1_melee Boolean
player_1_smg Boolean
player_1_grenade Boolean
player_1_shotgun Boolean
player_2_rifle Boolean
player_2_pistol Boolean
player_2_sniper Boolean
player_2_melee Boolean
player_2_smg Boolean
player_2_grenade Boolean
player_2_shotgun Boolean

In [20]:
total_df.count()

shape: (1, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ melee     ┆ smg       ┆ grenade   ┆ _shotgun │
│ u32       ┆ ---       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ u32       ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 236982    ┆ 236982    ┆ 236982    ┆ 236982    ┆ … ┆ 236982    ┆ 236982    ┆ 236982    ┆ 236982   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
total_df.row(0)

(6221,
 19.771653543307085,
 6207,
 19.661417322834644,
 567.8871158303689,
 139.44435312758435,
 212.87701382181572,
 0.0,
 100,
 False,
 True,
 False,
 1.881487083394461,
 -0.31732408776263543,
 False,
 'Pistol',
 52.53913130212391,
 179.51765979263553,
 0.0,
 97,
 False,
 True,
 False,
 0.431134986918039,
 0.31732408776263543,
 True,
 'Pistol',
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False)

In [22]:
total_df.row(118491)

(6221,
 19.771653543307085,
 6207,
 19.661417322834644,
 567.8871158303689,
 52.53913130212391,
 179.51765979263553,
 0.0,
 97,
 False,
 True,
 False,
 0.431134986918039,
 0.31732408776263543,
 True,
 'Pistol',
 139.44435312758435,
 212.87701382181572,
 0.0,
 100,
 False,
 True,
 False,
 1.881487083394461,
 -0.31732408776263543,
 False,
 'Pistol',
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False)

In [23]:
total_df.head(n=3)

shape: (3, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ melee     ┆ smg       ┆ grenade   ┆ _shotgun │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ bool      ┆ bool      ┆ bool      ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
total_df = total_df.drop("player_1_weapon")
total_df = total_df.drop("player_2_weapon")
total_df.head(n=3)

shape: (3, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ kill_tick ┆ kill_seco ┆ duel_tick ┆ duel_seco ┆ … ┆ player_2_ ┆ player_2_ ┆ player_2_ ┆ player_2 │
│ ---       ┆ nds       ┆ ---       ┆ nds       ┆   ┆ melee     ┆ smg       ┆ grenade   ┆ _shotgun │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ bool      ┆ bool      ┆ bool      ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221      ┆ 19.771654 ┆ 6207      ┆ 19.661417 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 8068      ┆ 34.314961 ┆ 7999      ┆ 33.771654 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 11130     ┆ 58.425197 ┆ 10879     ┆ 56.448819 ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
total_df.write_csv("./final_model_data.csv", separator=",", include_header=True)